// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQcE1SACaCI44elFiO2HUPywRvgRAa8ww',
    appId: '1:637951798588:web:bcd117c26f8c7cdd7f8239',
    messagingSenderId: '637951798588',
    projectId: 'getinlin',
    authDomain: 'getinlin.firebaseapp.com',
    storageBucket: 'getinlin.firebasestorage.app',
    measurementId: 'G-LDXTPNDHRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLgu7_utHLozYd08JwH4qPw143eohsD7g',
    appId: '1:637951798588:android:c5012c18e37002b97f8239',
    messagingSenderId: '637951798588',
    projectId: 'getinlin',
    storageBucket: 'getinlin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZz1kidQWjmK9qcWcp-3n0zd6tINz5uI',
    appId: '1:637951798588:ios:559afbc956a569de7f8239',
    messagingSenderId: '637951798588',
    projectId: 'getinlin',
    storageBucket: 'getinlin.firebasestorage.app',
    iosBundleId: 'com.example.getinline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsZz1kidQWjmK9qcWcp-3n0zd6tINz5uI',
    appId: '1:637951798588:ios:559afbc956a569de7f8239',
    messagingSenderId: '637951798588',
    projectId: 'getinlin',
    storageBucket: 'getinlin.firebasestorage.app',
    iosBundleId: 'com.example.getinline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQcE1SACaCI44elFiO2HUPywRvgRAa8ww',
    appId: '1:637951798588:web:8ad30714ec60fcc17f8239',
    messagingSenderId: '637951798588',
    projectId: 'getinlin',
    authDomain: 'getinlin.firebaseapp.com',
    storageBucket: 'getinlin.firebasestorage.app',
    measurementId: 'G-9CEEEZ7XXB',
  );
}
